
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: supabase
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-jwt
  namespace: supabase
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: supabase-jwt
  data:
    - secretKey: anonKey
      remoteRef:
        key: prod/supabase/keys
        property: anon-key
