
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-db
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: supabase-db
  data:
    - secretKey: password
      remoteRef:
        key: stackai-supabase-prod-supabase-db-credentials
        property: password
    - secretKey: username
      remoteRef:
        key: stackai-supabase-prod-supabase-db-credentials
        property: username
